name: wind-panel-app
channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.*
  - panel=1.4.4
  - bokeh=3.4.1
  - jupyter_bokeh=2.0.4
  - notebook
  - ipykernel
  - pytest
  - hypothesis